language: ruby
rvm:
 - 2.5.1
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa -pbkdf2"
  - "eval `ssh-agent`"
  - "ssh-add config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"
